### ISSUE TITLE
Creation of 2021 ITUC Global Rights Index Dataset

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/EmbodiedSuffering_Toolkit#20]
#### Description:
Creation of the International Trade Union Confederation (ITUC) 2021 Global Rights Index dataset. The purpose of including this dataset is to include data surrounding respect for workers' rights. Each of the included countries are rated on a scale of 1-5+, with 5+ having the most egregious working conditions.

![image](https://user-images.githubusercontent.com/34316256/185991349-942ae136-9e1d-49c1-8420-f00b04e3dc55.png)

Per the comments on this issue and PR #23 , the following entries will be added to the Country enum in the Embodied Suffering Toolkit:
-Hong Kong
-Taiwan
-Kosovo

*Democratic Republic of Congo, Eswatini, Honduras, Bangladesh and South Sudan (already in the enum)

**Comment by LLOUIE19** [comment]
I reviewed the spreadsheet. I made a correction to Ireland which should have been a 1 but was listed as a 2. 

In regards to some of the duplicate entries:

- The Democratic Republic of Congo (DRC) and Congo are two distinct nations. Both have different histories that have shaped their current state of affairs, and it accounts for the difference in their ratings. The DRC's history as a Belgian colony likely has shaped its sociopolitical atmosphere, making it not conducive for workers' rights. There were atrocious crimes committed against the people of the DRC. The Congo was a colony of France (Not that any form of colonization was good, just that the history of the DRC is notably horrific).  Moreover, the Congo is also smaller country than the DRC and uses a different currency. 
- South Sudan and Sudan are also two distinct nations. South Sudan obtained independence in 2011. 

Is it possible to create new enum's for these countries? Given that we hope that there will eventually be more granularity in our datasets, we will likely have to separate these countries anyway. 

In regards to Hong Kong and Taiwan, are there no enums for them since they are not recognized by the UN? Let me know if that is correct. Thanks!
